version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST} 
    networks:
      - "net"

  db:
    platform: "linux/x86_64"
    image: "mysql:8.3"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "net"

networks:
  net:
    driver: "bridge"