// Code generated by mockery v2.40.1. DO NOT EDIT.

package usecases

import (
	mock "github.com/stretchr/testify/mock"
)

// IProductDeleteUseCaseMock is an autogenerated mock type for the IProductDeleteUseCaseMock type
type IProductDeleteUseCaseMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: productDeleteInput
func (_m *IProductDeleteUseCaseMock) Execute(productDeleteInput ProductDeleteInput) error {
	ret := _m.Called(productDeleteInput)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ProductDeleteInput) error); ok {
		r0 = rf(productDeleteInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProductDeleteUseCaseMock creates a new instance of IProductDeleteUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductDeleteUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductDeleteUseCaseMock {
	mock := &IProductDeleteUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
